services:
  ganache:
    build:
      context: .
      dockerfile: Dockerfile.ganache
    ports:
      - "8545:8545"

  truffle:
    build:
      context: .
      dockerfile: Docker.truffle
    volumes:
      - .:/app
    depends_on:
      - ganache
    environment:
      - NETWORK=development
      - HOST=http://ganache:8545

  react-app:
    image: node:18
    working_dir: /frontend
    ports:
      - "5173:5173"
    volumes:
      - .env:/frontend/.env
      - .:/frontend
      - /frontend/node_modules
    depends_on:
      - ganache
    command: |
      sh -c "
      npm install && npm run dev;     
      "
